const TokenAddress = {
  USD: {
    address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    name: "USD Coin",
    symbol: "USDC",
    decimals: 6,
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v/logo.png",
    tags: ["verified", "strict", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: "7dGbd2QZcCKcTndnHcTL8q7SMVXAkp688NTQYwrRCrar",
    mint_authority: "BJE5MMbqXjVwjAF7oxwPYXnTXDyspzZyt4vwenNw5ruG",
    permanent_delegate: null,
    minted_at: null,
    extensions: {
      coingeckoId: "usd-coin",
    },
  },
  JUPITER: {
    address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    name: "Jupiter",
    symbol: "JUP",
    decimals: 6,
    logoURI: "https://static.jup.ag/jup/icon.png",
    tags: ["verified", "strict", "birdeye-trending", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: null,
    mint_authority: null,
    permanent_delegate: null,
    minted_at: "2024-01-25T08:54:23Z",
    extensions: {
      coingeckoId: "jupiter-exchange-solana",
    },
  },
  "WRAPPED SOL": {
    address: "So11111111111111111111111111111111111111112",
    name: "Wrapped SOL",
    symbol: "SOL",
    decimals: 9,
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png",
    tags: ["verified", "strict", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: null,
    mint_authority: null,
    permanent_delegate: null,
    minted_at: null,
    extensions: {
      coingeckoId: "wrapped-solana",
    },
  },
  BONK: {
    address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    name: "Bonk",
    symbol: "Bonk",
    decimals: 5,
    logoURI: "https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACsT_q6wqwf5cSY7I",
    tags: ["verified", "strict", "birdeye-trending", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: null,
    mint_authority: null,
    permanent_delegate: null,
    minted_at: null,
    extensions: {
      coingeckoId: "bonk",
    },
  },
  RAYDIUM: {
    address: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    name: "Raydium",
    symbol: "RAY",
    decimals: 6,
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R/logo.png",
    tags: ["verified", "strict", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: null,
    mint_authority: null,
    permanent_delegate: null,
    minted_at: null,
    extensions: {
      coingeckoId: "raydium",
    },
  },
  JITO: {
    address: "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
    name: "JITO",
    symbol: "JTO",
    decimals: 9,
    logoURI: "https://metadata.jito.network/token/jto/image",
    tags: ["verified", "strict", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: null,
    mint_authority: null,
    permanent_delegate: null,
    minted_at: "2023-11-27T20:41:24Z",
    extensions: {
      coingeckoId: "jito-governance-token",
    },
  },
  USDT: {
    address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    name: "USDT",
    symbol: "USDT",
    decimals: 6,
    logoURI:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.svg",
    tags: ["verified", "strict", "community"],
    created_at: "2024-04-26T10:56:58.893768Z",
    freeze_authority: "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
    mint_authority: "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
    permanent_delegate: null,
    minted_at: null,
    extensions: {
      coingeckoId: "tether",
    },
  },
  "Binance Staked SOL": {
    address: "BNso1VUJnh4zcfpZa6986Ea66P6TCp59hvtNJ8b1X85",
    name: "Binance Staked SOL",
    symbol: "BNSOL",
    decimals: 9,
    logoURI:
      "https://arweave.net/LepI-hea-JrbLMb4L_HpMzaq9k0aHY2-lVSGiBtwvFM?ext=png",
    tags: ["lst", "verified"],
    created_at: "2024-09-10T03:47:30.706774Z",
    freeze_authority: null,
    mint_authority: "75NPzpxoh8sXGuSENFMREidq6FMzEx4g2AfcBEB6qjCV",
    permanent_delegate: null,
    minted_at: "2024-08-26T06:04:34Z",
    extensions: {
      coingeckoId: "binance-staked-sol",
    },
  },
} as const;

export { TokenAddress };
